#!/usr/bin/env python3
"""
Derive the segment map from the unpacked image's relocation table.

A relocation site whose patched word sits directly after a 9A opcode is the
segment half of `call far ptr seg:ofs`, so that paragraph holds code. Every
other relocated segment value is a far data pointer. That test, not entropy or
zero-density, is what settles which region is which.

Segment names are the paragraph offset into the image, which is also
`runtime CS - load` -- so 0abe seen in Spice86 with load 017d is seg_0941.
tools/addr.py does that conversion so nobody does it in their head.

    tools/segmap.py [start-unpacked.exe]

Caveat, and it is a real one: each code segment is declared as running to the
next one down. That is right for entry points and wrong for a function that
runs past the next declared base, which will then be listed under that segment
at a different offset. The relocation table names the segments the program
calls into; it cannot name their lengths.
"""
import struct
import sys

path = sys.argv[1] if len(sys.argv) > 1 else \
    "ishar_legend_of_the_fortress_DOSGamer.com/start-unpacked.exe"
d = open(path, "rb").read()
nreloc = struct.unpack_from("<H", d, 6)[0]
hdrpar = struct.unpack_from("<H", d, 8)[0]
if nreloc == 0:
    sys.exit(f"{path} has no relocations -- run tools/unpack.py first")
hdr = hdrpar * 16
img = d[hdr:]
entry_cs, entry_ip = struct.unpack_from("<H", d, 0x16)[0], struct.unpack_from("<H", d, 0x14)[0]

code, data, seeds = set(), set(), set()
for i in range(nreloc):
    ofs, page = struct.unpack_from("<HH", d, 0x1C + i * 4)
    p = page * 16 + ofs
    if p + 2 > len(img):
        sys.exit(f"relocation {i} points past the image: {p:#x} >= {len(img):#x}")
    seg = struct.unpack_from("<H", img, p)[0]
    if p >= 3 and img[p - 3] == 0x9A:
        code.add(seg)
        seeds.add((seg, struct.unpack_from("<H", img, p - 2)[0]))
    else:
        data.add(seg)

code.add(entry_cs)
seeds.add((entry_cs, entry_ip))
paras = sorted(code)
print(f"// {len(paras)} code segments, {len(data - code)} data-only, "
      f"image {len(img):#x} -- generated by tools/segmap.py")
print(f"// entry {entry_cs:04x}:{entry_ip:04x}\n")
for i, p in enumerate(paras):
    end = paras[i + 1] * 16 if i + 1 < len(paras) else len(img)
    # File offsets, not image offsets: chani loads the whole file, MZ header
    # included, so every range is biased by the header. Without this the listing
    # is shifted by 0x250 bytes and every annotation names the wrong byte.
    print(f"segment[seg_{p:04x}]:\n    type   = code\n"
          f"    load   = [0..]:exe[0x{hdr + p * 16:05x}..0x{hdr + end:05x}]\nend\n")
print(f"// far pointers into these paragraphs, never called: "
      f"{' '.join(f'{s:04x}' for s in sorted(data - code))}")
print(f"// {len(seeds)} far-call targets")
for s, o in sorted(seeds):
    print(f"attr[seg_{s:04x}:{o:04x}]: type = code")
