#!/usr/bin/env python3
"""Generate TOOLS.md from every tool's own docstring.

A hand-written tools table drifts: 64 of 87 tools were missing from CLAUDE.md's. A tool's
docstring cannot drift from the tool, so that is the source. A tool with no docstring is
reported as an error rather than listed blank -- writing one is the price of adding a tool.

    tools/toolsindex.py            write TOOLS.md
    tools/toolsindex.py --check    fail if TOOLS.md is stale or a docstring is missing
"""
import ast, os, re, sys
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOLS = os.path.join(HERE, "tools")
OUT = os.path.join(HERE, "TOOLS.md")

# Anything named after a roadmap task is a probe written for that task; the rest are
# the standing instruments.
TASK = re.compile(r"^t\d+[a-z0-9]*-")

def summary(path):
    """First line of the docstring, or None."""
    try:
        if path.endswith(".py"):
            doc = ast.get_docstring(ast.parse(open(path).read()))
        else:
            # A script without a .py name is still usually Python. Parse it as such first;
            # the regex fallback once matched the opening '"""' of a multi-line docstring
            # and returned an empty summary, which read as "no docstring" and led to a
            # second one being inserted above the real one.
            head = open(path, errors="replace").read(8000)
            try:
                doc = ast.get_docstring(ast.parse(head))
            except Exception:
                doc = None
            if not doc:
                m = re.search(r'^"""\s*\n?(.+?)$', head, re.M) or \
                    re.search(r"^#\s*(\S.*)$", head, re.M)
                doc = m.group(1) if m else None
    except Exception:
        return None
    if not doc:
        return None
    return doc.strip().split("\n")[0].strip()

def collect():
    rows = []
    for n in sorted(os.listdir(TOOLS)):
        p = os.path.join(TOOLS, n)
        if not os.path.isfile(p) or n.startswith(".") or n.endswith((".sh", ".pyc")):
            if not (n.endswith(".sh") and n != "disasm.sh"):
                pass
        if n.endswith(".pyc") or n == "__pycache__" or not os.access(p, os.R_OK):
            continue
        if not (n.endswith(".py") or os.access(p, os.X_OK)):
            continue
        rows.append((n, summary(p)))
    return rows

def render(rows):
    standing = [(n, s) for n, s in rows if not TASK.match(n)]
    probes = [(n, s) for n, s in rows if TASK.match(n)]
    L = ["# TOOLS.md", "",
         "Generated by `tools/toolsindex.py`. **Do not edit by hand** — each line is the",
         "first line of that tool's own docstring, so it cannot drift from the tool.", "",
         f"{len(rows)} tools: {len(standing)} standing instruments, {len(probes)} task probes.",
         "", "## Standing instruments", "", "| tool | what it does |", "|---|---|"]
    for n, s in standing:
        L.append(f"| `tools/{n}` | {s or '**no docstring**'} |")
    L += ["", "## Task probes", "",
          "Written for one roadmap task, kept because the method is often reusable.",
          "", "| tool | what it does |", "|---|---|"]
    for n, s in probes:
        L.append(f"| `tools/{n}` | {s or '**no docstring**'} |")
    return "\n".join(L) + "\n"

def main():
    rows = collect()
    missing = [n for n, s in rows if not s]
    text = render(rows)
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if missing:
            print("tools with no docstring:", ", ".join(missing))
            return 1
        if cur != text:
            print("TOOLS.md is stale; run tools/toolsindex.py")
            return 1
        print(f"ok: TOOLS.md lists all {len(rows)} tools")
        return 0
    open(OUT, "w").write(text)
    print(f"TOOLS.md: {len(rows)} tools" +
          (f"; {len(missing)} with no docstring: {', '.join(missing)}" if missing else ""))
    return 0

sys.exit(main())
